### ISSUE TITLE
LeishmanBeddoes::calcAlphaEquiv not necessary?

### ISSUE THREAD

**Issue by petebachant** [turbinesFoam/turbinesFoam#148]
This point was brought up by Anders Goude. This function was apparently part of the LB model to allow input as geometric angle of attack, which we do not do. We use an "actual" angle of attack computed by sampling the flow field. 

c.f. "Simulating Pitching Blade With Free Vortex Model Coupled With Dynamic Stall Model for Conditions of Straight Bladed Vertical Axis Turbines", Journal of Solar Energy Engineering, AUGUST 2015, Vol. 137

**Comment by petebachant** [comment]
Doing so initial testing with this is giving some favorable results. @andersgoude and @victormendoza83, have you guys been using this function for the pitching blade simulations?

**Comment by andersgoude** [comment]
We are still testing it. It appears that the behavoiur is a bit different from the vortex method, which uses a potential flow method to calculate the angle of attack.
Note that the current implementation of the LeishmanBeddoesSD model contains the parameter alphaAttachedCorrection, which determines if the correction should be active or not.

**Comment by petebachant** [comment]
Just added an option to turn this off, but it is left on by default.
