### ISSUE TITLE
Ideal Gaussian smearing parameter

### ISSUE THREAD

**Issue by petebachant** [turbinesFoam/turbinesFoam#149]
See http://arxiv.org/pdf/1511.04117.pdf

It seems a value of `0.25*chordLength_` may be ideal for foils. Maybe bluff bodies should be different--based on their wake momentum thickness.

**Comment by petebachant** [comment]
Some ad hoc testing is showing dividing the chord length by anything greater than 2 causes the solution to blow up.

**Comment by petebachant** [comment]
This also has an effect on grid dependence. When epsilon is set based on the mesh, there is a strong tendency towards higher C_P on coarser grids. Once epsilon is set based on the chord, i.e., remains constant when refining the grid, the opposite is true.

**Comment by petebachant** [comment]
It should also be investigated how the number of elements interacts with this. With a large epsilon, more elements may cause an over-application of force on the flow.

**Comment by petebachant** [comment]
Larger epsilon values also seem to reduce "noisiness" of the C_P time series.

**Comment by petebachant** [comment]
Should come up with a rule of thumb for the ideal number of elements per unit span for a given epsilon. Try plotting this out and arriving at a distribution that gets the overlaps of the Gaussian functions closest to a constant value of unity.

**Comment by petebachant** [comment]
One example case with instability: RM2 with `epsilon = chordLength/2`, and `nx = 64` for the mesh. Using `epsilon = chordLength` seems to always be stable.

**Comment by petebachant** [comment]
It also seems that maybe the Gaussian should be elliptical instead of spherical, with a the widths based on both the span and chord lengths.

**Comment by petebachant** [comment]
May want to use the largest of:

* Chord length/0.25
* Span length
* Momentum thickness from drag
* Some local mesh-based length

**Comment by petebachant** [comment]
Some sample data from UNH-RVAT case below (RANS). In general, a large projection width results in a higher `C_P`. 

`meshFactor = 1`:

![image](https://cloud.githubusercontent.com/assets/4604869/13054100/e80bffbc-d3d5-11e5-99df-648ac69164be.png)


`meshFactor = 1.5`:

![image](https://cloud.githubusercontent.com/assets/4604869/13054110/f46fdb98-d3d5-11e5-819a-44afbef50839.png)


`meshFactor = 2.0`:

![image](https://cloud.githubusercontent.com/assets/4604869/13054194/6606eb7a-d3d6-11e5-8ab6-29477d86050a.png)


With `meshFactor < 2.0`, the RVAT LES simulation becomes pretty unstable, with very noisy `C_P` values.

**Comment by petebachant** [comment]
I think I'm going to set `meshFactor = 2.0` by default, and allow changing this value in each `profileData` subdictionary entry.

**Comment by hcOnel** [comment]
> It also seems that maybe the Gaussian should be elliptical instead of spherical, with a the widths based on both the span and chord lengths.

I was also bugged about this; element span length seems not to be involved anywhere in the decision of epsilon, only chord length is considered. Or is it included in calculations and I'm missing?
Also, is the elliptical distribution idea implemented in the code? It looks line a spherical distribution.

**Comment by petebachant** [comment]
It is a spherical distribution currently. I assumed users would keep the span lengths small enough that spherical distributions would be okay.

**Comment by hcOnel** [comment]
I am currently trying to find out the following in the code, some help would be really appreciated;
1. Considering your sketch [here](https://github.com/turbinesFoam/turbinesFoam/wiki/Actuator-line-geometry), which point is counted as the center of Gaussian distribution per element? (element quarter chord, half chord or mounting point?)
2. Velocity at which point on the element (thus, which cell corresponding to that point) is considered for relative velocity?
3. Is the total force smeared guaranteed to be equal to calculated singular force (i.e. employing convolution)?
4. You said span length should be small, do you mean smaller span is better? It looks like a span length closer to the chord length could be better, since the distribution is spherical.

Thanks in advance.

**Comment by hcOnel** [comment]
> > Is the total force smeared guaranteed to be equal to calculated singular force (i.e. employing convolution)?
> 
> No, I don't think so.

Well, I think this is a critical case if the total force is not successfully passed to the flow field. That means wake calculations would not be accurate. I would like to check this, but as far as I know, only the force magnitude is printed for cells as `force.turbine#` variable. I'd like to print out x, y and z components of the forces calculated on cells to visualize them on Paraview. Is this an easy process? I could not find where I can do this in the code.
Thanks in advance.

**Comment by petebachant** [comment]
Take a look at the list of fields when you open up the case in ParaView. Force vectors should be written from all actuator lines.
