### ISSUE TITLE
normalCoefficient and chordwiseCoefficient missing from profileData.C

### ISSUE THREAD

**Issue by andersgoude** [turbinesFoam/turbinesFoam#181]
in profileData.H, the functions:
scalar normalCoefficient(scalar angleOfAttackDeg);
scalar chordwiseCoefficient(scalar angleOfAttackDeg);
are declared, but they are not implemented in profileData.C
Should the functions be implemented or removed? (I suggest implemented)

Please note that the direction of these will not match the normal and tangential directions of the turbine if the blades are mounted with a pitch angle

**Comment by petebachant** [comment]
I agree they should be implemented. I must have forgot. They do assume they are in the blade element coordinate system. You're right that some more arithmetic would be required to project them onto the turbine coordinate system.

**Comment by petebachant** [comment]
@andersgoude, if you do end up implementing these before I do, please create the `profileData-cn-cc` (or similar) branch starting from master, i.e.

```bash
$ git checkout master
# If you haven't already set the upstream remote, execute line below
$ git remote add upstream https://github.com/turbinesFoam/turbinesFoam.git
$ git pull upstream master
$ git checkout -b profileData-cn-cc
```

so I can merge it in more quickly without all of the new changes from the variable Re profile work you've been doing.

**Comment by petebachant** [comment]
This function should also be used in the function that returns lists of these, so the calculation doesn't appear twice.
