### ISSUE TITLE
Harmonic pitching does not center around 0 pitch angle

### ISSUE THREAD

**Issue by andersgoude** [turbinesFoam/turbinesFoam#188]
In the current implementation, the pitch angle is calculated from the pitch rate using a low order numerical scheme. Therefore, for large values of deltaT, the numerical error in the integration will cause a different mean value than 0 for the pitch angle. The error can be seen by running a fixed symmetric airfoil with harmonic pitching, which should generate a symmetric result.
A simple solution would be to use
`scalar deltaPitch = pitchAmplitude_/180.0*pi*(sin(omega*t) - sin(omega*(t - dt)));`
in addSup in actuatorLineSource.C, which in the current implementation will ensure that the pitch angles are according to the original specification. One could also consider having a setPitch function, that sets the absolute pitch angle.

**Comment by petebachant** [comment]
Thanks for the report and the solution! I added a test for this so when pitch controllers are implemented this doesn't crop up again.
