### ISSUE TITLE
print out the Simulation Results

### ISSUE THREAD

**Issue by mohsenboojari** [turbinesFoam/turbinesFoam#209]
how can we print the total thrust , torque , axial force , tangential force and total produced power for a turbine? is it possible with this solver?

**Comment by petebachant** [comment]
By default the power (`cp`), thrust (or drag, `cd`) and torque (`ct`) coefficients are written to CSV file in `postProcessing/turbines/{startTime}/{turbineName}.csv`. You can convert these to dimensional quantities by multiplying by the reference density, rotor area, and free stream velocity, e.g.,

    power = 0.5*rho*area*cp*freeStreamVelocityMag^3
