### ISSUE TITLE
Inconsistent patch names in the dict "tutorials/actuatorLine/static/system/extrudeMeshDict"

### ISSUE THREAD

**Issue by chengyu2015** [turbinesFoam/turbinesFoam#213]
In the lines 24 and 27 of dict [extrudeMeshDict ](https://github.com/turbinesFoam/turbinesFoam/blob/master/tutorials/actuatorLine/static/system/extrudeMeshDict) ,the patch names "front" and "back" are not consistent with the ones in the blockMeshDict-3D

**Comment by petebachant** [comment]
`extrudeMesh` is only meant to be run with the 2-D version of the case. Take a look at top of the `Allrun` script for the arguments used.

**Comment by chengyu2015** [comment]
From lines 32-35 of the script [Allrun](https://github.com/turbinesFoam/turbinesFoam/blob/master/tutorials/actuatorLine/static/Allrun),  it seems `extrudeMesh` will run no matter the case is 2D or 3D

**Comment by petebachant** [comment]
You're right! I will fix that shortly. Thanks for reporting.
