### ISSUE TITLE
Error in the file profile3D.sh

### ISSUE THREAD

**Issue by chengyu2015** [turbinesFoam/turbinesFoam#214]
Line 11 of the script [profile3D.sh](https://github.com/turbinesFoam/turbinesFoam/blob/master/tests/actuatorLineSource/profile3D.sh), there is no "blockMeshDict" in the folder [tutorials/actuatorLine/static/system](https://github.com/turbinesFoam/turbinesFoam/tree/master/tutorials/actuatorLine/static/system), it should be the file blockMeshDict-3D. So the code should be 
`cp $TUTORIAL_DIR/system/blockMeshDict-3D system/blockMeshDict-3D`

**Comment by petebachant** [comment]
Thanks for reporting this. I haven't used that script in a while!

**Comment by chengyu2015** [comment]
Very fast response, thank you
