### ISSUE TITLE
I am not sure mesh factor is right or not in actuatorLineElement.C

### ISSUE THREAD

**Issue by chengyu2015** [turbinesFoam/turbinesFoam#216]
From lines 205,223 and 224 of [actuatorLineElement.C](https://github.com/turbinesFoam/turbinesFoam/blob/master/src/fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.C), 
`      scalar meshFactor = GaussianCoeffs.lookupOrDefault("meshFactor", 2.0);
        epsilonMesh = 2.0*Foam::cbrt(V[posCellI]);
        epsilonMesh *= meshFactor; `
this leads to epsilon = 4* Delta_grid, while the suggested factor is 2? I am not sure about the code implementation...

**Comment by petebachant** [comment]
That would be true for a perfectly cubic cell. It is possible, however, in the `profileData` `GaussianCoeffs` subdictionary, to set `meshFactor` to be whatever you like for a given profile.
