### ISSUE TITLE
Compilation error with OpenFoam 3.0.1 and Ubuntu 16.04 

### ISSUE THREAD

**Issue by gdeskos** [turbinesFoam/turbinesFoam#234]
Hi Peter,

I recently tried to compile turbinesFoam with OpenFoam 3.0.1 on ubuntu 16.04 LT and I got this error back. 

`fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.C: In constructor ‘Foam::fv::actuatorLineElement::actuatorLineElement(const Foam::word&, const Foam::dictionary&, const Foam::fvMesh&)’:
fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.C:443:76: error: invalid initialization of non-const reference of type ‘Foam::label& {aka long int&}’ from an rvalue of type ‘Foam::label {aka long int}’
     addedMass_(mesh.time(), dict.lookupOrDefault("chordLength", 1.0), debug)
                                                                            ^
In file included from fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.H:49:0,
                 from fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.C:26:
lnInclude/addedMassModel.H:99:9: note:   initializing argument 3 of ‘Foam::addedMassModel::addedMassModel(const Foam::Time&, Foam::scalar, Foam::label&)’
         addedMassModel
         ^
/home/zd1515/OpenFOAM/OpenFOAM-3.0.1/wmake/rules/General/transform:8: recipe for target 'Make/linux64GccDPInt64Opt/fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.o' failed
make: *** [Make/linux64GccDPInt64Opt/fvOptions/actuatorLineSource/actuatorLineElement/actuatorLineElement.o] Error 1
make: *** Waiting for unfinished jobs....`

it appears that you are trying to assign a non-constant reference to a const reference "debug". Do you have an easy fix for that, without changing the definition of your function etc ?

Thanks in advance,
George

**Comment by petebachant** [comment]
I believe this should be fixed by #236. Let me know if it doesn't work out.
