### ISSUE TITLE
a question about blade sectioning

### ISSUE THREAD

**Issue by koshatnik** [turbinesFoam/turbinesFoam#242]
I am trying to figure out how elementProfiles work in axialFlowTurbineALSource and crossFlowTurbineALSource, i.e, how is the radial position of each elementProfile determined? Because nElements and number of elementProfiles entries can be different in the code, as well as number of elementData entries. Are they unconditionally interpolated according to the number of entries? Say, if profileX covers 43% of the radial span, do I have to enter 43 lines of profileX and 57 lines of other profiles?

**Comment by petebachant** [comment]
The number of elements must be divisible by the number of entries in `elementProfiles`. For example, in the axial-flow turbine tutorial, there are 14 entries in `elementProfiles` and 28 elements, so the first two are the `cylinder` profile: https://github.com/turbinesFoam/turbinesFoam/blob/master/tutorials/axialFlowTurbineAL/system/fvOptions#L62

For your example, you could technically have 3 elements, placing one at 43% span. However, keep in mind that the elements are placed between the points defined in `elementGeometry`. Let me know if that doesn't make sense.

**Comment by koshatnik** [comment]
No warnings or errors popped up when I changed the number of elementProfiles into a non divisible number, that was the reason for my confusion. But your explanation is clear, I will enter a divisible number anyway. Thanks so much for the answer!
