### ISSUE TITLE
rotation direction is always the same regardless of the blade profile

### ISSUE THREAD

**Issue by koshatnik** [turbinesFoam/turbinesFoam#244]
To do a simple test, I have modelled a 2-blade wind turbine. Blade has;
- constant (NACA0012) airfoil profile along the span,
- no twist (constant pitch) along the span.
I expect the turbine to turn in opposite directions for 12 and -12 degrees of constant pitch but the rotation was in CCW direction (when seen from the upwind zone), regardless of the pitch.
Am I understanding something wrong here? I kept all other settings the same.
Thanks in advance.

**Comment by petebachant** [comment]
You'll need to reverse the `axis` definition for the turbine. It rotates in the axis direction according to the right hand rule.

**Comment by koshatnik** [comment]
Thanks for the answer. But if the rotation direction is pre-defined, how is the total forces calculated on each blade segment has an effect on the motion?

**Comment by petebachant** [comment]
Technically, the blade forces don't affect the motion. Essentially it is assumed that the turbine uses a perfect fixed speed controller.

**Comment by koshatnik** [comment]
Ok I understand, but I am a bit confused now.
- There is the actual free stream velocity during the unsteady calculation.
- There are defined `freeStreamVelocity` and `tipSpeedRatio` parameters in fvOptions. 
- And after all, there are actual velocity components around blade segments during the unsteady calculation.
All of these seems to over-constraint the problem. So, the turbine rotates with a fixed rotational speed (I guess calculated from freeStreamVelocity and tipSpeedRatio?) regardless of other parameters, but the calculated C_p and C_t changes? What happens between the cut-in and rated wind speed zone?

**Comment by koshatnik** [comment]
Or what happens when the actual free stream velocity changes in an unsteady case, at the same time there is a fixed `freeStreamVelocity` parameter is defined?

**Comment by petebachant** [comment]
There is no feedback controller functionality. It is in the issue tracker as a future enhancement, however. Something like NREL's SOWFA may be more applicable to your particular simulation goals if you need controller modeling.

**Comment by koshatnik** [comment]
Thanks again.
Upon running the simulation with
`        axis                (1 0 0);`
I get the following error related to `endEffects`;
```
PIMPLE: iteration 1
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#3  acos in "/lib/x86_64-linux-gnu/libm.so.6"
#4  Foam::fv::axialFlowTurbineALSource::calcEndEffects() at ??:?
#5  Foam::fv::axialFlowTurbineALSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, int) at ??:?
#6  ? at ??:?
#7  ? at ??:?
#8  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#9  ? at ??:?
```
Active model is 
```
        endEffects
        {
            active          on;
            endEffectsModel Glauert; // Glauert || Shen || liftingLine
            GlauertCoeffs
            {
                tipEffects  on;
                rootEffects on;
            }
        }
```
same as in the axialFlowTurbineAL tutorial. The code runs without error with `endEffects active off`. Can be a bug?

**Comment by petebachant** [comment]
It could be a bug, but I'm really not sure. I'd have to dig into the source code and see where there might be something like division by zero. Maybe the pitch or chord direction has the wrong sign with the flipped axis, but I think there's a local coordinate system based on the axis and vertical direction.

**Comment by koshatnik** [comment]
I've been playing with the axialFlowTurbine tutorial you have provided, with only 1 blade to see the effects clearly. To make my turbine CW rotating (like most commercial turbines do), I have tried reversing the `axis` and reversing the `tipSpeedRatio` separately, and investigated pressure contours at the turbine plane.
* Reversing axis: endEffects gives a fatal error, so I have turned it off. Pressure contour makes sense (low towards the rotation direction) but overall different than the reverse axis. Here is a gif comparing two results:
https://media.giphy.com/media/kwZ8PNS3smbVGrKBBJ/giphy.gif
* Reversing tipSpeedRatio: Completely meaningless results.
I conclude that changing the blade profile is not necessary since otherwise I would get an inverse pressure contour around the blade. I don't think boundary conditions has an effect on different pressure contours.
I also tried reversing the verticalDirection parameter, all it has done is to change the initial location of the blade.

**Comment by petebachant** [comment]
You can try turning on the debug switches in `controlDict`, then the solver logs will print things like the chord directions of each element, etc., to ensure they are created in the proper direction. There very well could be a bug there, since I've mainly tested rotating in one direction.

**Comment by koshatnik** [comment]
UPDATE: The thing seen in the GIF in my last post is caused by the **positioning of the tower**. When the axis is reversed, the coordinates of tower (and probably hub) should be changed since they are defined in the reference frame of the turbine. Contour plots and `postProcessing` results are **almost** the same when tower and hub are removed in my last run. So I did not do a debug yet but I guess that verifies that blade/airfoil parameters are oriented correctly? Yet, this is for the case in which `endEffects` are turned off.
Additional question: In the tutorial, hub elementData is given as:
```
            elementData
            ( // axial distance, height, diameter
                (0 0.09 0.09)
                (0 -0.09 0.09)
            );
```
If tower and hub are defined in the rotor reference frame, does not this give a vertical-axis cylinder (instead of a horizontal-axis cylinder, which a hub looks like)?

**Comment by petebachant** [comment]
Aha! Nice debugging work! The hub _should_ be defined in the rotor coordinates, where axial distance is literally along the axis. Really, in this example the hub is just a single point actuator line, so it's "shape" would be a spherical Gaussian; not really a cylinder. There's a limit to how much geometry these actuator lines can really capture, though there are some ideas out there for adding more.

**Comment by koshatnik** [comment]
Thanks. Yet, I could not find the cause of `endEffects` error despite digging in the source code...
