### ISSUE TITLE
possible minor error in axialFlowTurbineALSource.C

### ISSUE THREAD

**Issue by daa-mec** [turbinesFoam/turbinesFoam#264]
Hi, I am in the process of reading the turbinesFoam library, and I think there might be an error in line 164 from the axialFlowTurbineALSource.C 

`        scalar radiusCorr = sqrt(magSqr(chordMount - 0.25)*chordLength + magSqr(radius));`

I think there is a couple of parentheses missing and that it should be:

`        scalar radiusCorr = sqrt(magSqr(   (   chordMount - 0.25)*chordLength  ) + magSqr(radius));`

Maybe I am just missing something. 

Anyways I want to thank all you for this great work. When I finish I will like to do some benckmark with NREL experiment and MEXICO rotor.

**Comment by petebachant** [comment]
Looks like you could be right! I'll need to search through the code and see if anything similar is done anywhere else.
