### ISSUE TITLE
I sit possible to use ABL inlet condition?

### ISSUE THREAD

**Issue by ethren** [turbinesFoam/turbinesFoam#280]
Is it possible to simulate a non-uniforme inlet flow with atmospheric boundary layer?

**Comment by petebachant** [comment]
Sure. OpenFOAM has an atmospheric boundary layer inlet boundary condition that will work just fine. You'll just need to set the free stream velocity for the turbine appropriately based on some reference velocity.

**Comment by ethren** [comment]
Dear Pete,
In this case, if I have a non-uniform velocity at the inlet, then which velocity should I specify in fvOptions

**Comment by petebachant** [comment]
Sometime like the hub height mean velocity should be appropriate.

**Comment by ethren** [comment]
Sorry but, for VAWTs what is the hub hight?

**Comment by petebachant** [comment]
Ah, I didn't realize you were talking about a VAWT. I suppose you would use the height where the turbine's anemometer would be located, which would depend on the design.

**Comment by ethren** [comment]
Thank you for your reply. Actually, after a quick research, I found that some authors could use the equator hight, rotor diameter, ...etc as a **hub height**.
By the way, I can't understand what do you mean by an anemometer location.

**Comment by petebachant** [comment]
Equator height makes sense. Anemometer location would be where the wind speed sensor is placed on the actual turbine, but that would not likely be used for controlling TSR, for example.

**Comment by ethren** [comment]
I have no experience with large-scale VAWT, I have only a small prototype with a height, `h = 0.30m`
