### ISSUE TITLE
Empty graph in a tutorial

### ISSUE THREAD

**Issue by ethren** [turbinesFoam/turbinesFoam#282]
In `turbinesFoam/tutorials/actuatorLine/static` when I run it,  for example : `./Allrun 3D 10` . The simulation runs fine but when I invoke the `plot.py` script, I get the empty graph as follows no mater how I run the simulation:
![empty_graph](https://user-images.githubusercontent.com/38412653/57619740-fea7fb80-7586-11e9-829e-3a18a3f10604.PNG)

**Comment by petebachant** [comment]
I see you closed the issue. How did you get it working?

**Comment by ethren** [comment]
@petebachant: Sorry, I just increased the number of elements `nElements` in `fvOptions` file :)
