### ISSUE TITLE
Isssue with OpenFoam 1906

### ISSUE THREAD

**Issue by chandukec** [turbinesFoam/turbinesFoam#290]
Hi,
I am trying to install turbineFoam in my workstation and I am already having openFoam 1906. It is throwing lots of error. Is the turbineFoam not compatible with the OpenFoam 1906 or I am missing something terribly?

**Comment by petebachant** [comment]
I've never tried it, so there very well may be an issue. Can you post the error messages here? (enclosed in three backticks to make it monospace)

````
```
my error message here!
```
````

**Comment by chandukec** [comment]
Thanks for your reply, here are the error messages:

fvOptions/crossFlowTurbineALSource/crossFlowTurbineALSource.C: In member function ‘virtual void Foam::fv::crossFlowTurbineALSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, Foam::label)’:
fvOptions/crossFlowTurbineALSource/crossFlowTurbineALSource.C:575:17: error: ambiguous overload for ‘operator*=’ (operand types are ‘Foam::volVectorField {aka Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>}’ and ‘int’)
     forceField_ *= 0;
fvOptions/crossFlowTurbineALSource/crossFlowTurbineALSource.C: In member function ‘virtual void Foam::fv::crossFlowTurbineALSource::addSup(const volScalarField&, Foam::fvMatrix<Foam::Vector<double> >&, Foam::label)’:
fvOptions/crossFlowTurbineALSource/crossFlowTurbineALSource.C:653:17: error: ambiguous overload for ‘operator*=’ (operand types are ‘Foam::volVectorField {aka Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>}’ and ‘int’)
     forceField_ *= 0;

**Comment by burgreen** [comment]
I compiled this just today for v1906.

In three files, replace these instances:
```
    // forceField_ *= 0;
    forceField_ *= dimensionedScalar("zero",forceField_.dimensions(),0.0);
```

In actuatorLineElement.C:
```
        // word dsName = dsDict.lookup("dynamicStallModel");
        word dsName; dsDict.lookup("dynamicStallModel") >> dsName;
```

**Comment by petebachant** [comment]
@burgreen is that include statement for v7 compatible with v1906 as well?

**Comment by burgreen** [comment]
@petebachant, v1906 likes the include statement too.

**Comment by burgreen** [comment]
Although running the axialFlowTurbineALSource gives the below error. Something is off by a square or square root. 
```
    f: 0.145403789855
Calculating force contribution from actuatorLineElement turbine.blade1.element0
    position: (0 0.00375551608908 0.027999260685)
    chordDirection: (0 0.991124272034 -0.132938622622)
    spanDirection: (0 -0.132938622622 -0.991124272034)
    elementVelocity: (0 3.733234758 -0.500735478544)
    planformNormal: (1 0 0)
    inflowVelocity: (10 0 0)
    relativeVelocity: (10 -3.733234758 0.500735478544)
    Reynolds number: 9617.28132062
    Geometric angle of attack (degrees): 69.3602808282
    Angle of attack (uncorrected, degrees): 69.3602808282
    Angle of attack (corrected, degrees): 69.3602808282
    liftDirection: (0.352490468666 0.92750936059 -0.124406010775)
    dragDirection: (0.935815403538 -0.349361859156 0.046859597392)
    force (per unit density): (0.0329271669215 -0.0122924844034 0.00164878006855)
    epsilon (mesh-based): 0.183333082243
    sphereRadius: 0.495347168962


--> FOAM FATAL ERROR: 
Different dimensions for '(a += b)'
     dimensions : [0 2 -4 0 0 0 0] != [0 1 -2 0 0 0 0]


    From function bool Foam::checkDims(const char*, const Foam::dimensionSet&, const Foam::dimensionSet&)
    in file dimensionSet/dimensionSet.C at line 55.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::error::abort() at ??:?
#2  Foam::dimensionSet::operator+=(Foam::dimensionSet const&) const at ??:?
#3  Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh>::operator+=(Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&) at ??:?
#4  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::operator+=(Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&) at ??:?
#5  Foam::fv::actuatorLineElement::addSup(Foam::fvMatrix<Foam::Vector<double> >&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>&) at ??:?
#6  Foam::fv::actuatorLineSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, int) at ??:?
#7  Foam::fv::axialFlowTurbineALSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, int) at ??:?
#8  ? at ??:?
#9  ? at ??:?
#10  __libc_start_main in /lib64/libc.so.6
#11  ? at ??:?
Aborted
```

**Comment by petebachant** [comment]
Started working on this in #291, but still having issues tracing down the dimensional incompatibility. If anyone feels like helping out, you can check out the `of7` branch.

**Comment by chandukec** [comment]
Thanks Burgreen for the valuable input. It finally installed in OF-v1906.

**Comment by chandukec** [comment]
Hello, 
Trying to run the tutorial case of actuatorLine/pitching, but getting the same error (with OF-V1906):
--> FOAM FATAL ERROR: 
Different dimensions for '(a += b)'
     dimensions : [0 2 -4 0 0 0 0] != [0 1 -2 0 0 0 0]


    From function bool Foam::checkDims(const char*, const Foam::dimensionSet&, const Foam::dimensionSet&)
    in file dimensionSet/dimensionSet.C at line 55.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::error::abort() at ??:?
#2  Foam::dimensionSet::operator+=(Foam::dimensionSet const&) const at ??:?
#3  Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh>::operator+=(Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&) at ??:?
#4  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::operator+=(Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&) at ??:?
#5  Foam::fv::actuatorLineElement::addSup(Foam::fvMatrix<Foam::Vector<double> >&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>&) at ??:?
#6  Foam::fv::actuatorLineSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, int) at ??:?
#7  ? at ??:?
#8  ? at ??:?
#9  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
#10  ? at ??:?

**Comment by petebachant** [comment]
@chandukec there are some issues with consistency of units and a fix is underway. See #291 and please comment if you figure out the problem.

**Comment by chandukec** [comment]
I am trying to install the turbinesFoam for the Centos but unable to source it. Specifically, we are having a cluster with some nodes, and we run the openFoam through the PBS script. This cluster have CentOS operating system in it. We run the openFoam by sourcing it through the source line in the PBS script, through 
source ./cshrc
source /usr/local/openFoam/setup1906.csh
Could you kindly help how this could be extended for the CentOS?

**Comment by petebachant** [comment]
It should be the same as installing anywhere else. Clone turbinesFoam somewhere you have permissions (somewhere inside your home directory), source the OpenFOAM cshrc, and run `Allwmake`. OpenFOAM should be able to find the libs after that.

**Comment by chandukec** [comment]
Thanks it worked.
