### ISSUE TITLE
Mesh extrusion for a 2D case

### ISSUE THREAD

**Issue by Yoorthiziri** [turbinesFoam/turbinesFoam#293]
https://github.com/turbinesFoam/turbinesFoam/blob/d4f7b961c4c9bcec9a5e21fe49e3efa3a114ef4c/tutorials/actuatorLine/static/Allrun#L34-L37

Hello,
Why `extrudeMesh` is used in this case to extrude mesh when the case is supposed to be 2D? the mesh is already 3D when it is generated by `blockMesh`.

Thank you

**Comment by petebachant** [comment]
I forget where I first saw this pattern, but it is extruded since `snappyHexMesh` refines uniformly in all directions, and therefore might have more than one cell across the thickness. Extruding ensures the entire domain is one cell thick.
