### ISSUE TITLE
Is there any update regarding installing the turbinesFoam in OpenFoam 1906

### ISSUE THREAD

**Issue by chandukec** [turbinesFoam/turbinesFoam#294]
Hello, 
This is a general query regarding the installation of  turbinesFoam in OpenFoam 1906. Previously, in #290 , it was installed successfully but showing some errors while running the cases, and the #290 is closed and moderator has initialized the #291 , so is the issue been resolved? Any comments/suggestions to use  turbinesFoam?

**Comment by petebachant** [comment]
Yes. It should be compatible as of merging #291. If you `git pull origin master` you'll obtain the latest code and it should compile. Please open a new issue if there are errors.

**Comment by chandukec** [comment]
Thanks, it works!
