### ISSUE TITLE
Compatibility with OpenCFD releases

### ISSUE THREAD

**Issue by hcOnel** [turbinesFoam/turbinesFoam#296]
Hello,
OpenFOAM is being developed actively in two mediums, afaik:
1. OpenFOAM foundation: https://cfd.direct/ and https://openfoam.org/ where versions are named as 2.4.x, 5.x etc.
2. OpenCFD and ESI Group: https://www.openfoam.com/ where versions are named as v1712, v1906 etc.

I should clarify that I do not know much about the differences between those two, in terms of development, programing and usage. I know that turbinesFoam works on foundation versions and I am actively using it, but I wonder whether or not turbinesFoam work on OpenCFD versions too, i.e. v1706.

Thanks in advance,
Hüseyin

**Comment by petebachant** [comment]
It should work with the ESI version, but is not tested for in the current test suite. I did check recently that the latest version worked with v1906.
