### ISSUE TITLE
Prescribing hub elements for the axialFlowTurbineAL case

### ISSUE THREAD

**Issue by CallumG-Ed** [turbinesFoam/turbinesFoam#306]
Hi,

based on the axial flow tutorial and the comments towards the end of #244 I'm interested to know the functionality of the hub element setup.

```
        hub
        {
            nElements   1;
            elementProfiles (cylinder);
            elementData
            ( // axial distance, height, diameter
                (0   0.09   0.09)
                (0  -0.09   0.09)
            );
        }
```
Based on the above am I to take it that this prescribes a cylinder whose centre line is from (0,-0.09) to (0,0.19) in the local turbine reference frame and has diameter of 0.09? And because nElements equals 1 it just acts as a single point at (0,0).

This being the case could I specify a cylinder (actuator line) in the streamwise direction (like in reality) something like:

```
        hub
        {
            nElements   2;
            elementProfiles (cylinder);
            elementData
            ( // axial distance, height, diameter
                (0       0    0.09)
                (-0.14   0    0.09)
            );
        }
```

In this case would I get an element at (0,0) and (-0.14,0)? 

I have tried the two cases above and plotted turbine force along the turbine axis. The force at centre hub (0,0,0) is slighty higher in the second case. And in the second case the turbine force continues to increase slightly beyond x=0, while the original case decreases. So I think this supports my assumption maybe?

**Comment by petebachant** [comment]
It sounds like that is approximating what you're trying to achieve. You could turn on the debug switches in `controlDict` for `actuatorLine` and `actuatorLineElement` to ensure the "chords" are pointed in the right direction, but maybe a slice of flow velocity will tell the story better.

Note the the hub rotates, but a nacelle wouldn't, though including a nacelle isn't implemented at the moment: https://github.com/turbinesFoam/turbinesFoam/blob/master/src/fvOptions/axialFlowTurbineALSource/axialFlowTurbineALSource.C#L447

**Comment by CallumG-Ed** [comment]
Hi Pete, that's very true I had overlooked the fact the hub is rotating and the nacelle wouldn't be so I suppose I'm better discounting the nacelle afterall. Thanks again for the good information and for your time!

Cheers
Callum
