### ISSUE TITLE
[QUESTION] Can blades 2 & 3 be written to post processing directory?

### ISSUE THREAD

**Issue by CallumG-Ed** [turbinesFoam/turbinesFoam#311]
Hi,

I'm interested in knowing if there is an easy way to write out information for each actuator line element on each blade for the axial flow turbine. I know the default is to write information for blade 1 only.

I'm actually interested in having timeseries for root bending moment for each blade, as well as time series for representative forces at each actuator line element (for each blade).

Would be interested if this is easily implemented.

Thanks in advance. 
Callum

**Comment by petebachant** [comment]
Yep, this is easy to achieve. If you look in most of the tutorials you'll see

```c++
        blades
        {
            blade1
            {
                writePerf   true;
                writeElementPerf true;
                nElements   28;
                elementProfiles
                (
                    cylinder
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                    S826
                );
                elementData
                (
                    #include "elementData"
                );
            }
            blade2
            {
                $blade1;
                writePerf   false;  // <-- delete this line
                writeElementPerf false;  // <-- delete this line
                azimuthalOffset 120.0;
            }
            blade3
            {
                $blade2;
                azimuthalOffset 240.0;
            }
        }
```

If you delete the two lines noted in the comments, you'll get blade/element performance data written for all.

**Comment by CallumG-Ed** [comment]
Great! Thanks Pete!!

Just 2 more quick questions if i can be so bold :-) . Does "root_dist" refer to the distance between the actuator line centre and the blade root. With the actuator line centre being halfway between say station0 and station1 for the first element?

Also I'm assuming forces fx, fy, and fz are in reference to the global coordinate system? And so the 2D blade station forces need transforming into local blade station coordinates?

Thanks again for answering all my questions, it's really appreciated!!

**Comment by petebachant** [comment]
>Does "root_dist" refer to the distance between the actuator line centre and the blade root. With the actuator line centre being halfway between say station0 and station1 for the first element?

Yep, I believe that's true. I don't remember if it's nondimensionalized, but that should be easy to determine.

>Also I'm assuming forces fx, fy, and fz are in reference to the global coordinate system? And so the 2D blade station forces need transforming into local blade station coordinates?

Yep, also true.

**Comment by CallumG-Ed** [comment]
Great stuff, thanks Pete!!

**Comment by petebachant** [comment]
No worries. Sounds like this is resolved so I'm going to close. Feel free to reopen if something isn't working right.
