### ISSUE TITLE
Questions about the findCell() function in actuatorLineElement

### ISSUE THREAD

**Issue by GetChaos** [turbinesFoam/turbinesFoam#312]
Hi Pete and others,
I'm coming up with a problem of the actuatorLineElement.findCell() function. When calculating epsilonMesh, findCell() can't give out a cell label. It always return a value -1. But I'm quite sure the source point was in the computational domain. 
The problem only happens in parallel computations, when number of subdomain is relative large, like 8 to 40. So I think it may be caused by the meshBoundBox_ in findCell(). I try to print out what actually findCell find out in the subdomains by the following sentence:
`Pout<< "findcell: " << mesh_.findCell(location) << endl;` 
The information is:

[2] Looking for cell containing (0 0.892125 0) inside bounding box:
[2] (-0.305555828411 -2.72855272993e-07 -1.00000027286) (0.00444471729972 1.83000027286 1.00000027286)
[2] findcell: -1
[3] Looking for cell containing (0 0.892125 0) inside bounding box:
[3] (-0.0300002728553 -2.72855272993e-07 -1.00000027286) (0.280000272855 1.83000027286 1.00000027286)
[3] findcell: 10165

It seems like findCell() really find a cell in processor3 and returns the cell label, but in processor2 it can't find the cell so it return -1. And at last -1 is returned.  

Do you have any ideas about the issue? 

Thank you!

**Comment by GetChaos** [comment]
Hey guys, 
I think I figured out why the problem happened. Because the coordinates of different subdomains may be overlapped with each other,  even though the cells are not. 
So sometime when the point locates at the overlapping region of two subdomains, the following if statement in findCell() function will count both of the two subdomain
`if [(meshBoundBox_.containsInside(location))]`
       ` {`
          `  if (debug)`
          `  {`
             `   Pout<< "Looking for cell containing " << location`
                 `   << " inside bounding box:" << endl`
                 `   << meshBoundBox_ << endl;`
            `}`
            `return mesh_.findCell(location);`
        `}`  
Therefore it will find twice in the two subdomains respectively, and the cell could only be found in one subdomain. In other subdomain, -1 will be returned. If the real cell label is covered by -1, the finally value is -1.
I can feel that using boundBox will be more efficient in finding cell label, but I'm really not familiar with it. I don't know how to fix the problem with boundBox. So I just rewrite findCell() as such:

`Foam::label Foam::fv::memberALElement::findCell`
`(`
   ` const point& location`
`)`
`{`
	   ` label cellIndex;`
	   ` cellIndex = mesh_.findCell(location);`
              `  reduce(cellIndex, maxOp<label>());`
             `   Info<< "findcell: " << cellIndex << endl;`
		`return cellIndex;`
`}`
If you guys have any good idea about the function, please must tell me. Thank so much!

**Comment by petebachant** [comment]
Ah, yes. I believe it was initially written like that but the parallel speedup was poor searching for the cell on all processes. Sounds like there could be a combination of the two approaches--only search for the cell if it's in the bounding box, but still handle the case where `cellIndex = -1`. Do you think you could put together a PR to implement that?

**Comment by GetChaos** [comment]
Hi Pete,
Thank you for your reply! 
Yes, I have done a PR, but I'm not sure if I did it right, I'm not familiar with git, you can check it. However I found that the function I wrote still didn't work well. At some points, there will be error messages like: 

[33] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[33] #1  Foam::sigSegv::sigHandler(int) at ??:?
[33] #2  ? in "/lib64/libc.so.6"
[33] #3  Foam::polyMeshTetDecomposition::cellTetIndices(Foam::polyMesh const&, int) at ??:?
[33] #4  Foam::cellPointWeight::findTetrahedron(Foam::polyMesh const&, Foam::Vector<double> const&, int) at ??:?

But I don't think there are tetrahedron cells in my mesh. Then I printed out the cell found out in each subdomain, the information is (40 subdomains):
:
:
[7] findcell: -1
[18] findcell: -1
:
[17] findcell: -1
[21] findcell: 47911
:
[1] findcell: 17233
[19] findcell: -1
:
:
And the final cellIndex returned is 47911. So it seems like the function found two cells in two subdomains respectively, and the large number was returned. But I'm not sure if it is the cell I want. Now I'm stuck here and really don't know what to do. 
Do you have any good idea about it? Thank you!

**Comment by GetChaos** [comment]
I think I can close this issue. I'm sure where the problem is. It was just because I accidentally commented out a reduce command in function calcProjectionEpsilon(). 
Sorry for my carelessness! And thank you for your fast reply!
