### ISSUE TITLE
Questions about the dimension of the forceField in actuatorLineElement.C

### ISSUE THREAD

**Issue by GetChaos** [turbinesFoam/turbinesFoam#315]
Hi Pete,
    I have a question about the applyForceField function in actuatorLineElement.C. In the function, the force field was finally calculated as forceVector_*factor. Factor is the projected function that can be expressed as:
![image](https://user-images.githubusercontent.com/74336098/100818306-ce83be80-3484-11eb-8b78-97d353355932.png)
   My question is from the expression of the factor, we can figure out its unit is m-3. Furthermore the unit of forceVector_ is N. Therefore, the finally unit of forceField is N/m3. The forceField will be added to the source term of the governing equation. But I think for the finite volume method, we use integral form of the governing equations, the physical quantities are calculated on every cell. So the unit of the source term of a cell should be N, which is different from the unit of the forceField we add in. 
   I'm not sure what the problem is. Could you help me? Thanks a lot!

**Comment by petebachant** [comment]
Good question. I had always assumed that projection factor to be non-dimensional itself, but spread over space with a given length scale. For the latter question, I believe source terms are applied as force per unit volume, since the units of the terms in the momentum equation are per unit density (?). Both the Gaussian projection and the units of the force vectors I emulated from NREL's SOWFA without thinking too much about the dimensions, but it's certainly worth working through them all to ensure they're consistent.

**Comment by GetChaos** [comment]
Hi Pete,
    Thank you for your reply. These days, I tried to find out the problem. And I think the problem may be in the operator+=(). In actuatorALSource.C, the following sentence add source to eqn:
`eqn += forceField_`
   I searched the operator+=() in fvMatrix class, and the defination of the operator is:

 void Foam::fvMatrix<Type>::operator+=
 (
     const DimensionedField<Type, volMesh>& su
 )
 {
     checkMethod(*this, su, "+=");
     source() -= su.mesh().V()*su.field();
 }

We can see that the field is mutiplied by the volume before added to the source. Therefore the volume is multiplied in openfoam automatically. Print the dimensions of eqn we can also get: [0 4 -2 0 0 0 0], and that represents dimForce/dimDensity. Thanks so much for your continue responses for my questions. My English is not so good, hope you don't mind.

**Comment by petebachant** [comment]
Thanks for investigating! I will close this issue for now, but feel free to open if you think something is wrong in the code.
