### ISSUE TITLE
How to use hysteresis loops of Lift / drag in this library

### ISSUE THREAD

**Issue by SignificantCell2** [turbinesFoam/turbinesFoam#318]

**Comment by petebachant** [comment]
That sounds like it would be a new type of dynamic stall model, with a lookup table for the hysteresis (as a function of pitch rate?). Alternatively, you could use one of the Leishman--Beddoes variants, and try to fit the parameters to your data. I did something similar fitting the constants in the coefficient curves here: https://github.com/petebachant/Leishman-Beddoes-constants
