### ISSUE TITLE
Using "axialFlowTurbineALSource" for generating currents(Mixer usage)

### ISSUE THREAD

**Issue by farzadmech88** [turbinesFoam/turbinesFoam#324]
Dear Pete Bachant
First of all, I want to thank you for your helps either here or LinkedIn with your helpful comments. I have implemented turbinefoam inside the MPPICFOAM and it works fine as shown in below video;
0-3 seconds; jet starts to work
3-6 seconds; turbine and nozzles starts to work
6-9 seconds; bubble injection starts; 

https://user-images.githubusercontent.com/54691016/123880128-f0b9be00-d939-11eb-857a-f3700a8eb069.mp4

**In this simulation, I have used S826(from your implemented library) and it works fine. Now, I want to use my own mixer for this purpose. My mixer is this one;**

![image](https://user-images.githubusercontent.com/54691016/123881241-34152c00-d93c-11eb-8a03-8ab4e877a2bb.png)

in the next section, I am going to provide fvOption data which I use for my new simulation(And I got error).

**Comment by farzadmech88** [comment]
Here, I provide the exact location of turbine and initial jet(as a stimulator);
![image](https://user-images.githubusercontent.com/54691016/123881827-6d01d080-d93d-11eb-8d13-260db80f72be.png)

And below one is the fvOption;
`momentumSource2
{type            meanVelocityForce;
        active          on;            
        meanVelocityForceCoeffs
    {   timeStart   0.;
        duration    1000.;
        selectionMode   cellZone;        
        cellZone        CIRCLEinZ;   
        fields                  (U.water);
        Ubar         (0.0 0.0 -1.2); //freeStreamVelocity    //(0.0 0.0 -1.0);                
        relaxation  0.1; }}`

And this is the turbine characteristics;  
`
turbineMain
{
    type            axialFlowTurbineALSource;     
    active          on; //off; //off; //on;

    axialFlowTurbineALSourceCoeffs
    {
        fieldNames          (U.water);  
        selectionMode       cellSet; 
        cellSet             turbine;
        origin              (0.8125 0.75 0.75);   
        axis                (0 0 1);             
        verticalDirection   (0 1 0); 
        freeStreamVelocity  (0 0 -1.2);   //(0 0 -3); //Rotation(0.75Re)====> 719.7890 rpm = 75.376128 rad/s 
        tipSpeedRatio        9.422;       //11.6;     //tipSpeedRatio = {(speed of blade)/(Wind Speed)}===>(r*w[rad/s])/(wind speed)
        rotorRadius         0.15 ;        //0.35;     //===> (0.15*75.376128)/(1.2)===>11.3064192/1.2====>tipSpeedRatio = 9.422         

        dynamicStall
        {
            active          off;
            dynamicStallModel LeishmanBeddoes;
        }

        endEffects
        {
            active          off;    //on;
            endEffectsModel Glauert; // Glauert || Shen || liftingLine
            GlauertCoeffs
            {
                tipEffects  on;
                rootEffects on;
            }
            ShenCoeffs
            {
                c1          0.125;
                c2          21;
                tipEffects  on;
                rootEffects on;
            }
        }  

        blades
        {
            blade1
            {
                writePerf   true;
                writeElementPerf true;
                nElements   19; //28;
                elementProfiles
                (
                //  cylinder S826 S826 S826 S826 S826 S826 S826 S826 S826 S826 S826 S826 S826  
                //    cylinder       //Mark Muray data
                //    s1_075Re   //1
                //   s1_075Re   //1   
                    
                    
                    cylinder
                    s1_075Re   //1
					s1a_075Re  //2
					s2_075Re   //3
					s2a_075Re  //4
					s3_075Re   //5
					s3a_075Re  //6
					s4_075Re   //7
					s4a_075Re  //8
					s4b_075Re  //9
					s5_075Re   //10
					s5a_075Re  //11
					s5b_075Re  //12
					s6_075Re   //13
					s6a_075Re  //14
					s6b_075Re  //15
					s7_075Re   //16
					s7a_075Re  //17
					s8_075Re   //18
					s8a_075Re  //19
					s9_075Re   //20    

                );
                elementData
                (
                //    #include "elementData"
                
                // Blade element data
                
                
//axialDistance, radius, azimuth, chord, chordMount, Twist" 					
(0	0.078	0	0.10109588	0.25	14.99707058)     //1
(0	0.0835	0	0.10048288	0.25	14.21630666)
(0	0.89	0	0.09980976	0.25	13.43375340)
(0	0.96	0	0.09911008	0.25	12.66096309)
(0	0.1	0	0.09865394	0.25	12.17403633)
(0	0.106	0	0.09778477	0.25	11.51971488)	//6
(0	0.109	0	0.09719715	0.25	11.20717363)
(0	0.111	0	0.09674492	0.25	11.04198550)
(0	0.116	0	0.09528716	0.25	10.56053261)
(0	0.118	0	0.09455501	0.25	10.34565663)
(0	0.12	0	0.09373258	0.25	10.17417310)	//11
(0	0.124	0	0.09174303	0.25	9.79628201)
(0	0.127	0	0.08988820	0.25	9.47166556)
(0	0.131	0	0.08676393	0.25	8.95312542)
(0	0.134	0	0.08387748	0.25	8.86171644)
(0	0.136	0	0.08152122	0.25	8.65285990)		//16
(0	0.142	0	0.07118970	0.25	8.05930551)
(0	0.145	0	0.06236817	0.25	7.70428619)
(0	0.1475	0	0.05039778	0.25	7.35009664)
(0	0.15	0	0.02919500	0.25	6.83219268)     //20
);}
            blade2
            {
                $blade1;
                writePerf   false;
                writeElementPerf false;
                azimuthalOffset 120.0;
            }
            
             blade3
            {
                $blade2;
                azimuthalOffset 240.0;
            }
           
        }
         
         profileData
        {
           // S826
           // {
           //     data (#include "resources/foilData/S826_1e5_Ostavan");
           // }
           // cylinder
           // {
           //     data ((-180 0 1.1)(180 0 1.1));
           // } 
            
            cylinder
            {
                data ((-180 0 1.1)(180 0 1.1));
            } 
            
            s1_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s1_075Re.txt");
            }
            
            s1a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s1a_075Re.txt");
            }
            
            s2_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s2_075Re.txt");
            }
            
            s2a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s2a_075Re.txt");
            }
            
            s3_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s3_075Re.txt");
            }
            
            s3a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s3a_075Re.txt");
            }
            
            s4_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s4_075Re.txt");
            }
            
            s4a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s4a_075Re.txt");
            }
            
            s4b_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s4b_075Re.txt");
            }
            
            s5_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s5_075Re.txt");
            }
            
             s5a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s5a_075Re.txt");
            }
            
             s5b_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s5b_075Re.txt");
            }
            
             s6_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s6_075Re.txt");
            }
            
             s6a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s6a_075Re.txt");
            }
            
             s6b_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s6b_075Re.txt");
            }
            
            s7_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s7_075Re.txt");
            }
            
            s7a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s7a_075Re.txt");
            }
            
            s8_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s8_075Re.txt");
            }
            
            s8a_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s8a_075Re.txt");
            }
            
            s9_075Re
            {
                data (#include "resources/foilData/MarkMuray0.75Re/s9_075Re.txt");
            }
                        
        }
    }
}`

**Comment by farzadmech88** [comment]
Just for an example, I have put s1_075Re.txt as below;

```
// //alpha, cl, cd
(-10	-0.0413491	0.0118653)
(-9.5	-0.0397043	0.0111048)
(-9	-0.0395085	0.0104726)
(-8.5	-0.0389515	0.0097800)
(-8	-0.0390069	0.0091018)
(-7.5	-0.0384023	0.0083421)
(-7	-0.0371939	0.0075483)
(-6.5	-0.0352817	0.0067436)
(-6	-0.0326035	0.0059527)
(-5.5	-0.0291882	0.0052022)
(-5	-0.0251310	0.0045157)
(-4.5	-0.0205054	0.0039083)
(-4	-0.0152693	0.0034287)
(-3.5	-0.0097927	0.0029295)
(-3	-0.0042277	0.0025775)
(-2.5	0.0011047	0.0022821)
(-2	0.0064059	0.0020594)
(-1.5	0.0117361	0.0020259)
(-1	0.0169614	0.0020264)
(-0.5	0.0221557	0.0020331)
(0	0.0273257	0.0020442)
(0.5	0.0324736	0.0020593)
(1	0.0376009	0.0020780)
(1.5	0.0427084	0.0021002)
(2	0.0477971	0.0021259)
(2.5	0.0528682	0.0021554)
(3	0.0579241	0.0021890)
(3.5	0.0629690	0.0022274)
(4	0.0680126	0.0022719)
(4.5	0.0730915	0.0023281)
(5	0.0777519	0.0026057)
(5.5	0.0847190	0.0031108)
(6	0.0923975	0.0037325)
(6.5	0.0979956	0.0044240)
(7	0.1025430	0.0053821)
(7.5	0.1040980	0.0061223)
(8	0.1044760	0.0068890)
(8.5	0.1036260	0.0076624)
(9	0.1015510	0.0084224)
(9.5	0.0980317	0.0091276)
(10	0.0941344	0.0099656)
(10.5	0.0908141	0.0110392)
(11	0.0890687	0.0122790)
(11.5	0.0885283	0.0133260)
(12	0.0885299	0.0142619)
(12.5	0.0888933	0.0151244)
(13	0.0895109	0.0159298)
(13.5	0.0900682	0.0166612)
(14	0.0919642	0.0174111)
(14.5	0.0933000	0.0179384)
(15	0.0922104	0.0186791)

```
Now, I got below error;
![image](https://user-images.githubusercontent.com/54691016/123884025-22368780-d942-11eb-8b8a-1949841e7cee.png)

**Comment by farzadmech88** [comment]
Ok, I almost make it work, but I have a trouble with one parameter(chordMount). what is chordMount exactly?

![image](https://user-images.githubusercontent.com/54691016/124201336-b124da80-dacf-11eb-86f8-677984c277bc.png)


Thanks,
Farzad

**Comment by farzadmech88** [comment]
Ok, the same question with an extra question, what is 0.25 in below code;
![image](https://user-images.githubusercontent.com/54691016/124201773-c0f0ee80-dad0-11eb-8079-5d943b1f2d66.png)


Thanks,
Farzad

**Comment by petebachant** [comment]
> Ok, I almost make it work, but I have a trouble with one parameter(chordMount). what is chordMount exactly?

`chordMount` is the fraction of the chord through which the line that determine the blade span passes. It is labeled as "chord mount offset" here: https://github.com/turbinesFoam/turbinesFoam/wiki/Actuator-line-geometry

**Comment by farzadmech88** [comment]
Dear Pete
Thanks for you reply. All sections of the code with my generated data for the airfoil works fine except the one I will explain below;
![image](https://user-images.githubusercontent.com/54691016/124269097-58d2f480-db32-11eb-923d-c8d34855e2b5.png)

The problem rises here(when I use my own data for blade geometry);
![image](https://user-images.githubusercontent.com/54691016/124269421-c3843000-db32-11eb-939e-ae28a30d19cd.png)

and the error is this one;
![image](https://user-images.githubusercontent.com/54691016/124269635-0ba35280-db33-11eb-81d5-7b155561db1d.png)

What is this error? 

Thanks, 
Farzad

**Comment by petebachant** [comment]
That error is saying that the 4th element of that blade can't be found in the mesh. Is it possible the blade is too long and rotated outside the domain when using the tutorial geometry?

For using your own geometry, keep in mind that the points you're defining are at the edges of each profile section (rectangles below), so the list of profiles should be one less than the number of geometry points.

![image](https://user-images.githubusercontent.com/4604869/124475673-f9fabe80-dd6f-11eb-83ab-9db3d5faa530.png)

**Comment by farzadmech88** [comment]
Dear Pete Bachant
The problem is solved. There was a typo in my data which makes the diameter much larger the he domain. it was a typo in element 2 and I fixed it. Thanks. 
Lets I ask two other remaining questions which are crucial for me;
![image](https://user-images.githubusercontent.com/54691016/124519209-8775f700-dde0-11eb-9c82-2a3fb9838fa0.png)

First question: We have 3 geometry blades in the figure so it means we have two elementProfiles which I name them S826 and S926 and we need to have one profileData for angle of attack and Cd and Cl for these profiles. Also in this figure we have six elementsData as below;
a1, a2, a3, b1, b2, b3 which means each elementProfile has three elementData. Now;
```
nElements   2;
elementProfiles (S826 S926)
// Blade element data
// axialDistance, radius, azimuth, chord, chordMount, twist
(axialDistance(a1), radius(a1), azimuth(a1), chord(a1), chordMount(a1), twist(a1))
(axialDistance(a2), radius(a2), azimuth(a2), chord(a2), chordMount(a2), twist(a2))
(axialDistance(a3), radius(a3), azimuth(a3), chord(a3), chordMount(a3), twist(a3))
(axialDistance(b1), radius(b1), azimuth(b1), chord(b1), chordMount(b1), twist(b1))
(axialDistance(b2), radius(b2), azimuth(b2), chord(b2), chordMount(b2), twist(b2))
(axialDistance(a3), radius(a3), azimuth(a3), chord(a3), chordMount(a3), twist(b3))
```
So based on this data we have 3 element data on each element profile which code can interpolate between them if needed. Am I correct?

Thanks,
Farzad

**Comment by farzadmech88** [comment]
Second question;
My main purpose is to use turbinesFoam for mixer usage(below mixer);
![image](https://user-images.githubusercontent.com/54691016/124520926-cc505c80-dde5-11eb-9568-90fd551a8dde.png)

As we know, mixer must generate momentum and current itself, but right now I should generate an initial jet(as a stimulator) and then code works fine;
![image](https://user-images.githubusercontent.com/54691016/124521249-c444ec80-dde6-11eb-88e9-0de8a6384a5e.png)

I want to use the code without the initial jet but it gives me below error exactly at the beginning(it is a general error and not a FATAL error);
![image](https://user-images.githubusercontent.com/54691016/124521388-3b7a8080-dde7-11eb-9dc7-1457eb4599fa.png)

I believe this error arises since the angle of attack is too large when there is no initial jet and I do not have a data in that range. My main question is that is there any way to start the mixer without initial jet?


Thanks,
Farzad

**Comment by petebachant** [comment]
> First question: We have 3 geometry blades in the figure so it means we have two elementProfiles which I name them S826 and S926 and we need to have one profileData for angle of attack and Cd and Cl for these profiles. Also in this figure we have six elementsData as below;
> a1, a2, a3, b1, b2, b3 which means each elementProfile has three elementData. Now;
> 
> ```
> nElements   2;
> elementProfiles (S826 S926)
> // Blade element data
> // axialDistance, radius, azimuth, chord, chordMount, twist
> (axialDistance(a1), radius(a1), azimuth(a1), chord(a1), chordMount(a1), twist(a1))
> (axialDistance(a2), radius(a2), azimuth(a2), chord(a2), chordMount(a2), twist(a2))
> (axialDistance(a3), radius(a3), azimuth(a3), chord(a3), chordMount(a3), twist(a3))
> (axialDistance(b1), radius(b1), azimuth(b1), chord(b1), chordMount(b1), twist(b1))
> (axialDistance(b2), radius(b2), azimuth(b2), chord(b2), chordMount(b2), twist(b2))
> (axialDistance(b3), radius(b3), azimuth(b3), chord(b3), chordMount(b3), twist(b3))
> ```
> 
> So based on this data we have 3 element data on each element profile which code can interpolate between them if needed. Am I correct?

If you want to specify 6 geometry points, I would try 5 elements. Is there any reason you only want to use 2?

**Comment by farzadmech88** [comment]
> > First question: We have 3 geometry blades in the figure so it means we have two elementProfiles which I name them S826 and S926 and we need to have one profileData for angle of attack and Cd and Cl for these profiles. Also in this figure we have six elementsData as below;
> > a1, a2, a3, b1, b2, b3 which means each elementProfile has three elementData. Now;
> > ```
> > nElements   2;
> > elementProfiles (S826 S926)
> > // Blade element data
> > // axialDistance, radius, azimuth, chord, chordMount, twist
> > (axialDistance(a1), radius(a1), azimuth(a1), chord(a1), chordMount(a1), twist(a1))
> > (axialDistance(a2), radius(a2), azimuth(a2), chord(a2), chordMount(a2), twist(a2))
> > (axialDistance(a3), radius(a3), azimuth(a3), chord(a3), chordMount(a3), twist(a3))
> > (axialDistance(b1), radius(b1), azimuth(b1), chord(b1), chordMount(b1), twist(b1))
> > (axialDistance(b2), radius(b2), azimuth(b2), chord(b2), chordMount(b2), twist(b2))
> > (axialDistance(b3), radius(b3), azimuth(b3), chord(b3), chordMount(b3), twist(b3))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So based on this data we have 3 element data on each element profile which code can interpolate between them if needed. Am I correct?
> 
> If you want to specify 6 geometry points, I would try 5 elements. Is there any reason you only want to use 2?

Dear Pete Bachant
The reason that I use 2 elements(in my own geometry I have 20 elements and I think it works fine) is below figure;
![image](https://user-images.githubusercontent.com/54691016/125067205-d86d4000-e0ab-11eb-87bb-523ab5aece74.png)

What I understand from above geometry is that;
1) We have three(3) geometry points
2) We have two(2) elements(S826 - S926)
3) Each element has three(3) element data. **S826**(a1,a2,a3), **S926**(b1,b2,b3)
**I just want to know am I correct?**

About the second question which is my main question;
**How can I use turbinesFoam as a mixer without any initial jet? Is it possible to apply force on fluid just using the blades?**

Thanks,
Farzad

**Comment by petebachant** [comment]
> What I understand from above geometry is that;
> 
> 1. We have three(3) geometry points
> 2. We have two(2) elements(S826 - S926)
> 3. Each element has three(3) element data. **S826**(a1,a2,a3), **S926**(b1,b2,b3)

The square markers on the rectangular planforms are the elements, so we have 6 elements. We have only two profiles, however.

> How can I use turbinesFoam as a mixer without any initial jet? Is it possible to apply force on fluid just using the blades?

My intuition is that it should work since the blades are moving, so there should be a relative velocity and therefore a force and momentum source. If it doesn't work, I honestly don't know.

**Comment by farzadmech88** [comment]
> > What I understand from above geometry is that;
> > 
> > 1. We have three(3) geometry points
> > 2. We have two(2) elements(S826 - S926)
> > 3. Each element has three(3) element data. **S826**(a1,a2,a3), **S926**(b1,b2,b3)
> 
> The square markers on the rectangular planforms are the elements, so we have 6 elements. We have only two profiles, however.
> 
> > How can I use turbinesFoam as a mixer without any initial jet? Is it possible to apply force on fluid just using the blades?
> 
> My intuition is that it should work since the blades are moving, so there should be a relative velocity and therefore a force and momentum source. If it doesn't work, I honestly don't know.

**Comment by farzadmech88** [comment]
Thanks Dear Pete. I will dig in the code to see what is wrong when I start it without initial jet. I will write my findings here for you.

Thanks,
Farzad
