### ISSUE TITLE
Position of turbine.blade1.element0 not found in mesh

### ISSUE THREAD

**Issue by Adhyanth29** [turbinesFoam/turbinesFoam#364]
Hello all!

I was trying to run a H-VAWT simulation, heavily based on the tutorial case in openFoam v2106. However, in the pimpleFoam loop, it returns me the following error (highlighted in yellow).

![image](https://github.com/turbinesFoam/turbinesFoam/assets/77678593/6d0eb74b-38e3-484d-b1bf-d339f28492c5)

Although the turbine.blade1 has been sourced properly, it is still unable to run the simulation. Do you know what could be causing this issue?

The tutorial case ran perfectly. I am currently not running pimpleFoam with MPI. I am testing it serially before parallelising it.

Thanks!

**Comment by petebachant** [comment]
I've seen these errors before when using scotch decomposition of the mesh.
